### PR TITLE
setup ossf scorecard and codql workflow

### PR DESCRIPTION
**Pull request by mmorel-35**
Setup dependabot for github-actions
Pin actions versions 

Signed-off-by: Matthieu MOREL <matthieu.morel35@gmail.com>

### CODE REVIEW

**Comment by mmorel-35** [comment]
cc @phlax

**Review by phlax — APPROVED** [review]
lgtm, thanks @mmorel-35

**Comment by phlax** [comment]
cc @rulex123

**Review by rulex123 — APPROVED** [review]

**Review by phlax — APPROVED** [review]
lgtm, thanks @mmorel-35

**Pull request merged**
