### PR TITLE
Remove deprecated api v2

### PR DESCRIPTION
**Pull request by Automaat**
I hope this cover removal of most of the API v2. If anyone sees anything that should be removed or improved here after removing API v2, please let me know.

### CODE REVIEW

**Review by Ferdudas97 — DISMISSED** [review]

**Comment by rulex123** [comment]
@Automaat Is CI still broken due to the GPG issue you mentioned a few days ago? If so, has anybody looked more closely to troubleshoot what's wrong?

**Comment by Automaat** [comment]
@rulex123 Sorry for such a late reply, but I was a whole week on KubeCon and didn't have time to work on this issue. Yes, CI is still broken. I tried to troubleshoot this problem, but I didn't find anything worth noting. @mikegajda Maybe you have any idea on how to fix it?

**Comment by mikegajda** [comment]
:wave: i took a quick look, but i'm not familiar with the circleci setup at all, and I believe I don't have access to change things there since i'm not an official contributor to this project. Is there anything in specific you want me to look into?

**Comment by rulex123** [comment]
I am somewhat familiar with the CI build pipeline, since I have done some work on it fairly recently. However I am off for the next couple of weeks and most likely won't have any time to dig into the issue. I can take a look once I am back from vacation, but if anybody wants to do more troubleshooting in the meantime, absolutely feel free! :)

**Comment by rulex123** [comment]
@Automaat I did a bit of troubleshooting, and the issue is that when the CI pipeline runs on a branch different from `main`, the GPG-related env vars (key and passphrase) are not available. This results in the error you are seeing when the gpg commands are executed in the pipelines. Haven't got time to dig into why that is, but maybe you can take it from here and investigate more?

These env vars are defined in the CircleCI "Project settings": I thought they would be available to all builds, but maybe not?

**Comment by rulex123** [comment]
OK - I think I figured it ou :) @Automaat I will DM you on Slack about a way forward

**Pull request closed without merging**
