### PR TITLE
Updated protobuf definitions

### PR DESCRIPTION
**Pull request by nandu-vinodan**
Updates to latest Envoy API (as of Nov 1, 2019)

Followed the instructions: https://github.com/envoyproxy/java-control-plane#bring-api-up-to-date-with-data-plane-api

mvn verify passed locally.

### CODE REVIEW

**Comment by nandu-vinodan** [comment]
@snowp Hi, can you please look into this ?

**Comment by nandu-vinodan** [comment]
Thanks @snowp.
Also, can you please start the deployment of the new version ?

**Comment by nandu-vinodan** [comment]
@snowp, any update on the new maven release ?

**Comment by slonka** [comment]
I'll do a release later today when I'm in the office.

**Comment by nandu-vinodan** [comment]
Thanks @slonka !

**Comment by slonka** [comment]
0.1.20 released: https://oss.sonatype.org/#nexus-search;gav~io.envoyproxy.controlplane~java-control-plane~~~~kw,versionexpand @nandu-vinodan

**Pull request merged**
