### PR TITLE
build: JUnit 4.12 --> 5.1.0

### PR DESCRIPTION
**Pull request by sullis**
Signed-off-by: Sean Sullivan <ssullivan@gilt.com>

### CODE REVIEW

**Comment by ramaraochavali** [comment]
Agree with @joeyb . @sullis is there any other motivation for this upgrade other than being the latest?

**Comment by sullis** [comment]
I enabled the surefire provider for Junit5.  All checks have passed.

**Comment by joeyb** [comment]
@sullis - There's still a huge decrease in coverage due to this change.

Beyond that, can you give us some info on what use case you think will be handled better by junit5? There hasn't been much momentum in the Java community in moving towards junit5, so I would prefer to stick with junit4 unless there's some concrete reason for migrating.

Consumers of this library are free to use whatever testing lib they want, since junit is a test-scoped dependency.

**Comment by ramaraochavali** [comment]
I am closing this as there seems to be no immediate need/benefit of this upgrade. Feel free to open if there is a real need.

**Pull request closed without merging**
