### PR TITLE
Initial import from github.com/joeyb/java-control-plane

### PR DESCRIPTION
**Pull request by joeyb**

### CODE REVIEW

**Comment by joeyb** [comment]
@mattklein123 - This initial import includes the CircleCI config. Is there anything that we need to do to tell CircleCI to start running builds for this project, or will that happen automatically after the initial config gets merged?

**Comment by mattklein123** [comment]
@joeyb I turned on Circle. Can you push an empty commit or just rebase/force-push? It should run tests.

**Comment by ramaraochavali** [comment]
@mattklein123 looks like I do not have write access yet. Can you please provide that?

**Comment by mattklein123** [comment]
@ramaraochavali should be fixed.

**Pull request merged**
