### PR TITLE
Update api to v1 17

### PR DESCRIPTION
**Pull request by lukidzi**
- Update protobuf to v1.17
- Fix tests to work with v2/v3

We should make separate PR with V2 deprecation because Envoy since 1.17 doesn't support V2 configuration and requires flag to enable.

### CODE REVIEW

**Comment by sschepens** [comment]
@slonka @snowp @jakubdyszkiewicz can someone have a look at this and get a release out please?

**Comment by slonka** [comment]
I will review it on Monday at the latest.

**Review by slonka — APPROVED** [review]

**Comment by slonka** [comment]
@sschepens released `v0.1.28` 🎊

**Comment by sschepens** [comment]
@slonka thanks!!

**Pull request merged**
