### PR TITLE
Bring protos up-to-date with Envoy 19.1

### PR DESCRIPTION
**Pull request by baselica**
Seems this repository has been left alone for a long time. I updated the tooling to fetch the appropriate deps used by envoy 19.1, this meant adding OpenTelemetry and using a new Prometheus proto. Instead of manually diffing I deleted the old proto folder and added the new ones, meaning the diff will be weird.

Let me know if this is ok. I need the newer deps to do some authz stuff, but I didn't want to add the protos manually to my own repo. 

Let me know what you think!

### CODE REVIEW

**Comment by baselica** [comment]
Seems the build timed out. Passed before I updated a comment in https://github.com/envoyproxy/java-control-plane/pull/184/commits/f03ba9732e2acc13fd625f5130a1d029f06a57cf.

**Comment by slonka** [comment]
Hi, did you use the [instructions](https://github.com/envoyproxy/java-control-plane#bring-api-up-to-date-with-data-plane-api) provided in the repo?

**Comment by baselica** [comment]
@slonka I updated the SHA in EnvoyContainer, so should be all fine unless I should close this and wait for https://github.com/envoyproxy/java-control-plane/pull/186 to be merged?

**Comment by baselica** [comment]
Turns out that v19.1 won't allow the v2 API (duh), so had to kill the old v2 classes.

**Comment by baselica** [comment]
Even though this passes, there's probably a bunch of more things that need to be cleaned up in relation to v2.

**Comment by rulex123** [comment]
Closing this since the protos have been updated to v1.20.0 through another patch.

**Comment by liangyuanpeng** [comment]
> another patch.

Here > https://github.com/envoyproxy/java-control-plane/pull/200

**Pull request closed without merging**
