### PR TITLE
api: update to envoyproxy/envoy@8ddd3b7

### PR DESCRIPTION
**Pull request by dapengzhang0**
Update to envoyproxy/envoy@8ddd3b7
This update added java proto options `java_multiple_files` and `java_outer_classname` for all the envoy api proto files.

### CODE REVIEW

**Comment by dapengzhang0** [comment]
On my MacBook, the protoc worked, but it had some failures for javadoc and test. If I skip them the build success:
```
mvn verify -Dmaven.javadoc.skip -Dmaven.test.skip
```

The javadoc failure is:
```
[INFO] java-control-plane ................................. SUCCESS [  1.991 s]
[INFO] api ................................................ FAILURE [  1.926 s]
[INFO] cache .............................................. SKIPPED
[INFO] server ............................................. SKIPPED
[INFO] test ............................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.235 s
[INFO] Finished at: 2019-02-06T14:37:27-08:00
[INFO] Final Memory: 25M/90M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.0.0:jar (attach-javadocs) on project api: Execution attach-javadocs of goal org.apache.maven.plugins:maven-javadoc-plugin:3.0.0:jar failed. NullPointerException -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :api
```

The test failure is:
```
[main] ERROR org.testcontainers.dockerclient.DockerClientProviderStrategy - Could not find a valid Docker environment. Please check configuration. Attempted configurations were:
[main] ERROR org.testcontainers.dockerclient.DockerClientProviderStrategy -     UnixSocketClientProviderStrategy: failed with exception InvalidConfigurationException (ping failed). Root cause NoSuchFileException (/var/run/docker.sock)
[main] ERROR org.testcontainers.dockerclient.DockerClientProviderStrategy - As no valid configuration was found, execution cannot continue
[INFO] Running io.envoyproxy.controlplane.server.DiscoveryServerXdsIT
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0 s <<< FAILURE! - in io.envoyproxy.controlplane.server.DiscoveryServerXdsIT
[ERROR] io.envoyproxy.controlplane.server.DiscoveryServerXdsIT  Time elapsed: 0 s  <<< ERROR!
java.lang.ExceptionInInitializerError
	at io.envoyproxy.controlplane.server.DiscoveryServerXdsIT.<clinit>(DiscoveryServerXdsIT.java:68)

[INFO] Running io.envoyproxy.controlplane.server.DiscoveryServerAdsIT
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0 s <<< FAILURE! - in io.envoyproxy.controlplane.server.DiscoveryServerAdsIT
[ERROR] io.envoyproxy.controlplane.server.DiscoveryServerAdsIT  Time elapsed: 0 s  <<< ERROR!
java.lang.ExceptionInInitializerError
	at io.envoyproxy.controlplane.server.DiscoveryServerAdsIT.<clinit>(DiscoveryServerAdsIT.java:65)
```

**Comment by dapengzhang0** [comment]
I had exactly the same javadoc and test failures on Mac for current master/head.

**Comment by snowp** [comment]
Cool yeah those just seem related to docker not being available.

**Comment by rene-m-hernandez** [comment]
Soooo ... pretty sure this change alters the package name of all the generated POJOs?

**Pull request merged**
